FROM node:22-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
 
FROM base AS builder
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app
RUN pnpm add -g turbo
COPY . .
RUN turbo prune @repo/api --docker
 
FROM base AS installer
RUN apk add --no-cache libc6-compat
RUN apk update
WORKDIR /app
 
COPY .gitignore .gitignore
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
ENV CYPRESS_INSTALL_BINARY=0
RUN pnpm install
 
COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
 
RUN pnpm turbo run build --filter=@repo/api...
 
FROM base AS runner
WORKDIR /app
 
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs
 
# 复制构建后的文件
COPY --from=installer --chown=nextjs:nodejs /app/packages/api/dist ./packages/api/dist
COPY --from=installer --chown=nextjs:nodejs /app/packages/api/package.json ./packages/api/
COPY --from=installer --chown=nextjs:nodejs /app/config ./config
 
# 设置环境变量
ENV NODE_ENV production
 
# 运行tasks:prod命令
CMD ["pnpm", "-F", "@repo/api", "tasks:prod"]